language: node_js
node_js:
  - "4.2"
  - "stable"
script:
  - npm run lint
  - npm test
  - npm link --silent && npm link crawlkit-runner-axe --silent
  - for f in examples/*.js; do echo "• running '$f'" && travis_retry node $f > /dev/null; done
